version: "3"

services:
  dexosblog:
    image: dexos-blog:latest
    container_name: dexos-blog
    command: python3 manage.py runserver 0.0.0.0:9091
    ports:
      - "9091:9091"
    restart: always
    volumes:
      - ".:/app"

networks:
  default:
    external:
      name: dexos-blog
